---
Name: silverstripeelemental-slideshowconfig
---
Dynamic\ElementalFlexslider\Elements\ElementSlideshow:
  extensions:
    - Dynamic\FlexSlider\ORM\FlexSlider

Dynamic\FlexSlider\Model\SlideImage:
  extensions:
    - Dynamic\ElementalFlexslider\ORM\ElementSlideshowSlideDataExtension